require 'nytimes/movies/base'
require 'nytimes/movies/link'
require 'nytimes/movies/multimedia_link'
require 'nytimes/movies/critic'
require 'nytimes/movies/result_set'
require 'nytimes/movies/review'